### ISSUE TITLE
Audio and Video are confusing

### ISSUE THREAD

**Issue by marumari** [GoogleChrome/permission.site#7]
Especially since they are perfectly valid HTML5 tags.  Can we call them Microphone and Camera, respectively?  That's at least a lot less confusing to me.

I'd be happy to make a quick PR, if you're okay with that.

**Comment by lgarron** [comment]
Yeah, those make sense. We've also settled on those names for Chrome UI.

PR sounds good, although you'll have to sign the Google CLA for me to merge to this repo.

**Comment by marumari** [comment]
Okay, I can do that.  Where's the link to this Google thingie again?

**Comment by lgarron** [comment]
https://cla.developers.google.com/clas

**Comment by marumari** [comment]
Checking with my employer's lawyers to verify that everything is on the up
and up!

On Apr 7, 2016, at 8:34 PM, Lucas Garron <notifications@github.com> wrote:

https://cla.developers.google.com/clas

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/GoogleChrome/permission.site/issues/7#issuecomment-207163465>

**Comment by lgarron** [comment]
@marumari now that you've signed the CLA, would you like to do the honors? :-)

**Comment by lgarron** [comment]
Thanks for the PR!
